/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bl.SenderTabelModel;
import bl.SenderTabelRenderer;


/**
 *
 * @author stefan
 */
public class GUI_Radio_Stations extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Radio_Stations
     */
      private SenderTabelModel bl = new SenderTabelModel(); 
     
    public GUI_Radio_Stations() {
        initComponents();
        
tabel.setDefaultRenderer(Object.class, new SenderTabelRenderer());
           tabel.setComponentPopupMenu(PopupMenu);
           jScrollPane1.setComponentPopupMenu(PopupMenu);
            tabel.setModel(bl);
            visible();
            
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        PopupMenu = new javax.swing.JPopupMenu();
        pop_hinzu = new javax.swing.JMenuItem();
        pop_hide = new javax.swing.JMenuItem();
        pop_anz = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();

        pop_hinzu.setText("Hinzufügen");
        pop_hinzu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pop_hinzuActionPerformed(evt);
            }
        });
        PopupMenu.add(pop_hinzu);

        pop_hide.setText("Band verstecken");
        pop_hide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pop_hideActionPerformed(evt);
            }
        });
        PopupMenu.add(pop_hide);

        pop_anz.setText("Band anzeigen");
        pop_anz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pop_anzActionPerformed(evt);
            }
        });
        PopupMenu.add(pop_anz);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jScrollPane1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void visible()
    {
     if(bl.getRowCount() == 0)
    {
        
     pop_hide.setVisible(false);   
     pop_anz.setVisible(false);
     System.out.println("disable");
    }
     else
     { 
      pop_hide.setVisible(true);   
     pop_anz.setVisible(true);
     System.out.println("enable");
     }
    }
    private void pop_hinzuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pop_hinzuActionPerformed
        // TODO add your handling code here:
        //hinzu
        AddDialog_Radio dialog = new AddDialog_Radio(this, true);
        dialog.setVisible(true);
         if(dialog.isOkay()){
            bl.add(dialog.getSender());
        visible();
         }
    }//GEN-LAST:event_pop_hinzuActionPerformed

    private void pop_hideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pop_hideActionPerformed
        // TODO add your handling code here:
        //hide
    
    }//GEN-LAST:event_pop_hideActionPerformed

    private void pop_anzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pop_anzActionPerformed
        // TODO add your handling code here:
        //anz
    }//GEN-LAST:event_pop_anzActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Radio_Stations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Radio_Stations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Radio_Stations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Radio_Stations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Radio_Stations().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu PopupMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem pop_anz;
    private javax.swing.JMenuItem pop_hide;
    private javax.swing.JMenuItem pop_hinzu;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables
}
